[package]
name = "uak"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
surf = "1.0.3"
async-std = { version = "1.5.0", features = ["attributes"] }
